### ISSUE TITLE
Debugging in Tulsi not working with Objective-C

### ISSUE THREAD

**Issue by bkase** [bazelbuild/tulsi#16] opened 2017-05-17 21:33 UTC
Hi!

I couldn't get debugging to work out of the box in a full bazel project, so I created a simple pure Objective-C sample project and Xcode is not associating breakpoints with the source files in both lldbinit and dsym+dwarfpatcher cases. 

It was my assumption that this was consistently working, so I was surprised to see it not working for me. Maybe I've configured something improperly?

I uploaded a project that reproduces the issue:
https://github.com/bkase/debugging-tulsi-broken

Thanks!

**Comment by rahul-malik** [comment] 2017-09-08 05:10
@bkase - should this issue should be closed at this point?

**Comment by vmsp** [comment] 2018-02-17 16:57
I can't get it working on bazel's HEAD. Not even with @bkase fix.

**Comment by vmsp** [comment] 2018-05-20 15:30
Any updates on this?

I noticed that there's another similar issue but for Swift #15. Maybe either this one or the other one should be closed so we can track debugging support in a single place?

**Comment by vmsp** [comment] 2018-05-21 14:52
Yep, I just made one [here](https://github.com/vmsp/bug-report-tulsi) using Swift which is what I'm using right now. Its just a simplified example from the [rules_apple](https://github.com/bazelbuild/rules_apple/tree/master/examples/ios/HelloWorldSwift) repository.

It compiles and runs fine in the simulator but if I set a breakpoint at AppDelegate.swift:26 it doesn't start debugging and just keeps running.

I'm using
* Bazel build label: 0.13.0-homebrew
* Tulsi b46c744 (HEAD right now)
* Xcode 9.2

**Comment by DavidGoldman** [comment] 2018-05-21 15:13
Thanks, looking into this a bit, it does seem to be the same issue as reported in #15:

Grepping the generated dSYMs for path reveals that the files are referenced from the sandbox path: `/private/var/tmp/_bazel_davg/268d5f7b2ff558666a4bfe299b1746e9/sandbox/7915296318415141333/execroot/__main__/proj/AppDelegate.swift`

But Tulsi only tries to remap the path without the sandbox:

`/private/var/tmp/_bazel_davg/268d5f7b2ff558666a4bfe299b1746e9/execroot/__main__/`

Will need to dig a bit further to figure out why Bazel has a different path.

**Comment by DavidGoldman** [comment] 2018-05-21 15:14
#15 mentions a workaround -- adding `--strategy=SwiftCompile=standalone` to your project's Bazel build flags, mind trying that?

**Comment by vmsp** [comment] 2018-05-21 15:48
I added the flag to my `tools/bazel.rc` and it does seem to getting picked up correctly. In the XCode log I get
```
INFO: Reading rc options for 'build' from /Users/vitor/src/brief/tools/bazel.rc:
  'build' options: --strategy=SwiftCompile=standalone
```
But it still doesn't work.

**Comment by DavidGoldman** [comment] 2018-05-21 15:57
Just confirmed the workaround locally. You might need to remove and re-add the breakpoint that you set previously for it to work.

**Comment by vmsp** [comment] 2018-05-21 16:02
You're right, it does work! Re-adding the breakpoint wasn't enough, though. I had to `rm -rf bazel* tulsi*` and regenerate the XCode project.

Thanks for your help!

**Comment by DavidGoldman** [comment] 2018-11-28 15:17
Closing as this seems to be a duplicate of #52, which is resolved for ObjC. For Swift sources, #15 is still open and the recommendation for now is to use `--strategy=SwiftCompile=standalone` flag to Bazel.

**Closed by DavidGoldman** 2018-11-28 15:17 UTC
