### ISSUE TITLE
Build fails with "type 'XcodeVersionConfig' has no method availability()"

### ISSUE THREAD

**Issue by dinhviethoa** [bazelbuild/tulsi#125] opened 2020-01-24 18:39 UTC
I checked out master at 08e9799f7e2c599df32af04b5018ea627e742b33

First, there was an issue with latest version of Xcode, so I had to change .bazelrc to match the version.
Then, I hit the following issue:

```
$ ./build_and_run.sh
DEBUG: Rule 'build_bazel_rules_swift' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "02c0ceb0fd1e966710c3f803bfae5136909de197", shallow_since = "1579622252 -0800" and dropping ["branch"]
DEBUG: Call stack for the definition of repository 'build_bazel_rules_swift' which is a git_repository (rule definition at /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_apple/apple/repositories.bzl:30:9
 - /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_apple/apple/repositories.bzl:58:5
 - /Users/hoa/Tulsi/tulsi/WORKSPACE:15:1
DEBUG: Rule 'build_bazel_apple_support' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "501b4afb27745c4813a88ffa28acd901408014e4", shallow_since = "1577729628 -0800" and dropping ["branch"]
DEBUG: Call stack for the definition of repository 'build_bazel_apple_support' which is a git_repository (rule definition at /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_apple/apple/repositories.bzl:30:9
 - /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_apple/apple/repositories.bzl:51:5
 - /Users/hoa/Tulsi/tulsi/WORKSPACE:15:1
INFO: Build option --xcode_version has changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_swift_local_config/BUILD:9:1: in xcode_swift_toolchain rule @build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_swift_local_config/BUILD", line 9
		xcode_swift_toolchain(name = 'toolchain')
	File "/private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 533, in _xcode_swift_toolchain_impl
		_xcode_execution_requirements(<1 more arguments>)
	File "/private/var/tmp/_bazel_hoa/a7a4157a3abba821f65b7c0155b4a9bb/external/build_bazel_rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 448, in _xcode_execution_requirements
		xcode_config.availability()
type 'XcodeVersionConfig' has no method availability()
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '@build_bazel_rules_swift_local_config//:toolchain' failed; build aborted
INFO: Elapsed time: 2.520s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (20 packages loaded, 465 targets configured)
```

**Comment by DavidGoldman** [comment] 2020-01-24 18:52
This is a dupe of https://github.com/bazelbuild/tulsi/issues/122

**Closed by DavidGoldman** 2020-01-24 18:52 UTC
